GET http://localhost:3000/accounts

###
POST http://localhost:3000/accounts
Content-Type: application/json

{
    "name": "Account 1",
    "subdomain": "tenant1"
}


###
POST http://localhost:3000/accounts
Content-Type: application/json

{
    
}